version: '3.8'

services:
  suporte_back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9004:3000" # Porta externa 9002 mapeada para a aplicação no container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TZ=America/Sao_Paulo # Define o fuso horário
    command: npm start
