version: '3.8'

services:
  suporte_back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
